section .text

exit:
	xor		rdi, rdi
	mov		rax, 60
	syscall

string_length:
	xor		rax, rax
.loop:
	cmp		byte [rdi+rax], 0
	je		.end
	inc		rax
	jmp		.loop
.end:
	ret

print_string:
	push	rdi
	call	string_length
	pop		rsi
	mov		rdx, rax
	mov		rax, 1
	mov		rdi, 1
	syscall
	ret


print_char:
	push	rdi
	mov		rdi, rsp
	call	print_string
	pop		rdi
	ret

print_newline:
	mov		rdi, 0xA
	jmp		print_char


print_uint:
	mov		rax, rdi
	mov		rdi, rsp
	push	0
	sub		rsp, 16
	dec		rdi
	mov		r8, 10
.loop:
	xor		rdx, rdx
	div		r8
	or		dl, 0x30
	dec		rdi
	mov		[rdi], dl
	test	rax, rax
	jnz		.loop

	call	print_string
	add		rsp, 24
	ret


print_int:
	test	rdi, rdi
	jns		print_uint
	push	rdi
	mov		rdi, '-'
	call	print_char
	pop		rdi
	neg		rdi
	jmp		print_uint
	ret

string_equals:
    xor rax, rax
    ret


read_char:
    xor rax, rax
    ret

read_word:
    ret

; rdi points to a string
; returns rax: number, rdx : length
parse_uint:
    xor rax, rax
    ret

; rdi points to a string
; returns rax: number, rdx : length
parse_int:
    xor rax, rax
    ret


string_copy:
	push	rdi
	push	rsi
	push	rdx
	call	string_length
	pop		rdx
	pop		rsi
	pop		rdi

	cmp		rax, rdx
	jae		.too_long

	push	rsi

.loop:
	mov		dl, byte[rdi]
	mov		byte[rsi], dl
	inc		rdi
	inc		rsi
	test	dl, dl
	jnz		.loop

	pop		rax
	ret

.too_long:
	xor		rax, rax
	ret
